name: Test

on:
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CONTRIBUTING.md'
    branches:
      - main
  push:
    paths-ignore:
     - 'README.md'
     - 'CONTRIBUTING.md'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run unit tests
      run: |
        pytest tests/
    - name: Run acceptance tests
      run: |
        robot atests/